name: Zotero → Slack

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  post-new-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Python + jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run ZotBot
        id: run-zotbot
        env:
          ZOTERO_GROUP:      ${{ secrets.ZOTERO_GROUP }}
          ZOTERO_COLLECTION: ${{ secrets.ZOTERO_COLLECTION }}
          ZOTERO_API_KEY:    ${{ secrets.ZOTERO_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          chmod +x zotero2slack.py
          python zotero2slack.py \
            --group      $ZOTERO_GROUP \
            --collection $ZOTERO_COLLECTION \
            --api        $ZOTERO_API_KEY \
            --webhook    $SLACK_WEBHOOK_URL \
            --artifact   bot-zotero2slack.json \
            --channel    "#papers" \
            --username   "ZotBot" \
            --icon       ":female-scientist:"

      - name: Commit updated artifact
        if: steps.run-zotbot.conclusion == 'success'
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bot-zotero2slack.json
          git diff --quiet && echo "No changes to commit" || git commit -m "chore: update ZotBot artifact" && git push
